# Generated by Django 4.2.5 on 2023-09-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
